config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "host_user", to: "home#host_user"
  get "signup", to: "users#new"
  get "guest_login", to: "users#guest_login"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, except: [:new] do
    member do
      get "show_qrcode"
    end
  end
  resources :posts do
    member do
      get "show_qrcodes"
      get "activation_reset"
    end
    resources :items do
      member do
        get "activate_item"
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :remember_me
  has_many :posts, dependent: :destroy
  before_create :set_user_id

  # ユーザー名のバリデーション
  VALID_NAME_REGEX = /\A[a-zA-Z0-9]+\z/
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 30 },
  format: { with: VALID_NAME_REGEX }, if: :require_validation?

  # パスワードのバリデーション
  has_secure_password #validations: false
  # validate(if: :require_validation?) do |record|
  #   record.errors.add(:password, :blank) unless record.password_digest.present?
  # end
  # validates_length_of :password, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED, if: :require_validation?
  # validates_confirmation_of :password, allow_blank: true, if: :require_validation?
  validates :password, length: { minimum: 6 }
  #,if: :require_validation?


  # ランダムなremenberトークンを生成
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ハッシュ化した記憶トークンをDB（remember_digest）に保存する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # cookiesから渡されたトークンがダイジェスト(ハッシュ化されたトークン）と一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーの記憶ダイジェストを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  private

    # ランダムなユーザーIDを生成
    def set_user_id
      while self.id.blank? || User.find_by(id: self.id).present? do
        self.id = SecureRandom.base58
      end
    end

    # ゲストユーザーの作成
    def self.guest_login
      random_pass = SecureRandom.base36
      create!(name: "ゲストユーザー",
              password: random_pass,
              guest: true)
    end

    #ゲストユーザーのみバリデーションを解除（:name）
    def require_validation?
      return true if self.guest == false || self.guest == 0
      false
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy show_qrcode ]
  before_action :require_verified_account, only: %i[ edit update destroy ]
  before_action :require_same_user, only: %i[ show edit update destroy show_qrcode ]
  before_action :require_user, only: %i[ index ]
  before_action :user_got_items, only: %i[ show ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_url(@user), notice: "新規ユーザーが作成されました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: "ユーザー情報が更新されました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    redirect_to root_path, notice: "アカウントが削除されました", status: :see_other
  end

  def guest_login
    if current_user
      redirect_to current_user, alert: "すでにログインしています"  # ログインしている場合はゲストユーザーを作成しない
    else
      user = User.guest_login
      log_in user
      remember(user)
      redirect_to user, notice: "イベントに参加しました"
    end
  end

  def show_qrcode
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end

    # ゲストユーザーに対する制限（編集・削除の禁止）
    def require_verified_account
      if @user.guest == true || @user.guest == 1
        redirect_to @user
      end
    end

    def require_same_user
      if current_user != @user
        redirect_to root_path
      end
    end

    # 参加者が獲得したアイテム一覧を返す
    def user_got_items
      @got_items = Item.where(item_got_user: current_user.id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: "row", id: "userForm") do |f| %>

  <div class="mb-3 col-10 <%= user.errors.include?(:name) ? "validation_errors" : "" %>" id="userNameField">
    <%= icon("person-circle") %> <%= f.label "アカウント名(半角英数字)", for: "userName", class: "form-label required" %>
    <%= f.text_field :name, class: "form-control", id: "userName", placeholder: "アカウント名を入力してください" %>
    <%#= f.text_field :name, class: "form-control", id: "userName", placeholder: "アカウント名を入力してください", data: { controller: "form", action: "input->form#userName"} %>
    <%= render 'layouts/error_messages',class: "invalid-feedback", obj: user, key: :name %>
    <span class="mt-1" id="userError"></span>
  </div>

  <div id="userPasswordGroup">
    <div class="mb-3 col-10 <%= user.errors.include?(:password) ? "validation_errors" : "" %>" id="userPasswordField">
      <%= icon("key-fill") %> <%= f.label "パスワード", for: "userPassword", class: "form-label required" %>
      <%= f.password_field :password, class: "form-control", id: "userPassword", placeholder: "パスワードを入力してください" %>
      <%= render 'layouts/error_messages',class: "invalid-feedback", obj: user, key: :password %>
      <p id="passwordError"></p>
    </div>

    <div class="mb-4 col-10 <%= user.errors.include?(:name) ? "validation_errors" : "" %>" id="userPasswordField">
      <%= icon("key-fill") %> <%= f.label "パスワード(確認用)", for: "userPasswordConfirmation", class: "form-label required" %>
      <%= f.password_field :password_confirmation, class: "form-control", id: "userPasswordConfirmation", placeholder: "パスワードをもう一度入力してください" %>
      <%= render 'layouts/error_messages',class: "invalid-feedback", obj: user, key: :password_confirmation %>
      <p id="passwordConfirmationError"></p>
    </div>
  </div>

  <div class="mb-3">
    <%= f.submit class: "btn__basic__m btn__green", id: "userSubmit" %>
  </div>
  <div class="mb-5">
    <%= link_to "キャンセル", (user.new_record? ? host_user_path : current_user), class: "btn__basic__m" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>


</div>

app/views/users/edit.html.erb
<h1>ユーザー情報の編集</h1>

<%= render "form", user: @user %>

<hr>
<div class="mb-5">
  <%= link_to icon_with_text("trash", "アカウントを削除する"), @user, class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", signup_path %>

app/views/users/new.html.erb
<h1>新規アカウント作成</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<% if @user.guest? %>
<!--- ゲストユーザー用の表示 --->
<div class="text-center mb-4">
  <h2 class="mt-3">参加者 ID</h2>
  <div  class="text-bg-light py-2 shadow-sm">
    <h3 class="mt-2 text-danger"><%= @user.id %></h3>
  </div>
</div>

<hr>

<h2 class="mt-3 text-center">獲得した景品</h2>
<div class="card shadow mt-3 mb-4">
  <div class="card-header">
    <%= icon_with_text("table", "一覧") %>
  </div>
  <div class="text-center">
    <div class="card-body mx-3">
      <div class="row py-2">
        <div class="col-4 mt-auto fw-bold">
          景品No.
        </div>
        <div class="col-8 mt-auto fw-bold">
          景品名
        </div>
        <hr class="mt-2">
      </div>
      <div class="row">
        <% @got_items.each do |item| %>
          <div class="col-4 mt-auto">
            <%= item.item_number %>
          </div>
          <div class="col-8 mt-auto">
            <%= link_to item.name, post_item_path(item.post_id, item.id) %>
          </div>
          <hr class="mt-2" style="border: 1px solid #ccc">
        <% end %>
      </div>
    </div>
  </div>
</div>


<div id="qrCodeReader" class="mb-4 text-center">
  <a href="" class="btn__basic__l btn__w80 btn__green" id="qrCodeAppLink"><%= icon_with_text("qr-code", "QRコードリーダーを開く") %></a>
</div>

<script type="text/javascript">
  var qrCodeReader = document.querySelector("#qrCodeReader");
  var qrCodeAppLink = document.querySelector("#qrCodeAppLink");
  // iPhone or iPad
  if ( navigator.userAgent.indexOf('iPhone') > 0 || navigator.userAgent.indexOf('iPad') > 0 ){
    // qrCodeAppLink.href = "qrcode://";
    qrCodeAppLink.href = "https://apps.apple.com/jp/app/qr%E3%82%B3%E3%83%BC%E3%83%89%E3%83%AA%E3%83%BC%E3%83%80%E3%83%BC-%E3%82%B7%E3%83%B3%E3%83%97%E3%83%AB%E3%81%AAqr%E3%82%B3%E3%83%BC%E3%83%89%E3%83%AA%E3%83%BC%E3%83%80%E3%83%BC%E3%82%A2%E3%83%97%E3%83%AA/id1080558159?itsct=apps_box_link&itscg=30200";
  // Android
  } else if( navigator.userAgent.indexOf('Android') > 0 ){
    qrCodeAppLink.href = "https://play.google.com/store/apps/details?id=com.hopej.android.go";
  }
</script>

<% else %>
<!--- イベント主催者用の表示 --->
  <div class="mb-3">
    <h2><%= @user.name %>さんのイベント一覧</h2>
  </div>

  <!-- 一覧 -->
  <div class="card shadow mt-3 mb-5">
    <div class="card-header">
      <%= icon_with_text("table", "一覧") %>
    </div>

    <div class="card-body mx-3">
      <%= link_to icon_with_text("plus-circle", "イベントを追加"),
                      new_post_path,
                      class: "btn__basic__m btn__green mb-3 mt-1"
      %>
      <div class="row py-2">
        <div class="col-2 mt-auto fw-bold">
          No.
        </div>
        <div class="col-5 mt-auto fw-bold">
          イベント名
        </div>
        <div class="col-5 d-flex fw-bold justify-content-end">
          イベントの編集
        </div>
        <hr class="mt-2">
      </div>
      <div class="row">
        <% @user.posts.each_with_index do |post, index| %>
          <div class="col-2 mt-auto">
            <%= index + 1 %>
          </div>
          <div class="col-5 mt-auto">
            <%= link_to post.title, post %>
          </div>
          <div class="col-5 d-flex justify-content-end">
            <%= link_to icon_with_text("pencil-square", "編集"), edit_post_path(post) , class: "btn btn-outline-primary mx-2" %>
            <%#= link_to icon("trash"), post , class: "btn btn-outline-danger", data: { turbo_method: :delete} %>
          </div>
          <hr class="mt-2" style="border: 1px solid #ccc">
        <% end %>
      </div>

      <!-- <div class="d-flex justify-content-end mt-3">
        <%#= paginate @cats %>
      </div> -->
    </div>
  </div>

  <hr>
  <div class="mb-5 text-center">
    <%= link_to icon_with_text("qr-code","参加者ログイン用のQRコードを表示"), show_qrcode_user_path(@user), class: "btn__basic__l btn__w80"%>
  </div>
<% end %>

app/views/users/show_qrcode.html.erb
<div class="no_print mb-3">
  <%= link_to icon_with_text("box-arrow-in-left", "マイページに戻る"), current_user %>
</div>
<div class="no_print text-center">
  <a href="javascript:void(0)" class="btn__basic__l btn__w80 btn__green d-block mb-3" onclick="window.print();return false;"><%= icon_with_text("qr-code", "QRコードを印刷する") %></a>
  <p class="fw-bold text-danger">※倍率など細かな調整は印刷ダイアログにて行ってください。</p>
</div>

<div class="page text-center py-5" style="border: 1px solid #ccc">
  <h2 class="mb-3">参加者ログイン用QRコード</h2>
  <div class="p-3">
    <%= qrcode guest_login_path, 8 %>
  </div>
</div>