config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "host_user", to: "home#host_user"
  get "signup", to: "users#new"
  get "guest_login", to: "users#guest_login"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, except: [:new] do
    member do
      get "show_qrcode"
    end
  end
  resources :posts do
    member do
      get "show_qrcodes"
      get "activation_reset"
    end
    resources :items do
      member do
        get "activate_item"
      end
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  before_create :set_item_id, :set_item_number
  belongs_to :post

  validates :name, presence: true, length: { maximum: 50 }

  private
    # item用のidを生成
    def set_item_id
      while self.id.blank? || User.find_by(id: self.id).present? do
        self.id = SecureRandom.urlsafe_base64
      end
    end

    # ランダムな景品番号を生成
    def set_item_number
      post = self.post
      while self.item_number.blank? || post.items.find_by(item_number: self.item_number).present? do
        self.item_number = rand(1..9999).to_s
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy activate_item ]
  before_action :set_post
  before_action :require_same_user, only: %i[ edit update destroy ]
  before_action :set_item_got_user, only: %i[ show ], if: proc { !host_user? }
  before_action :require_user, only: %i[ index show ]


  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    @item.post = @post
    @item.item_state = "exist" if !@item.lose?
    if @item.save
      # redirect_to @item.post
      flash.now.notice = "景品が１件追加されました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    if @item.update(item_params)
      # redirect_to post_item_path(@item.post_id, @item.id), notice: "アイテムが更新されました"
      flash.now.notice = "景品情報が更新されました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    redirect_to post_path(@post), notice: "アイテムが削除されました", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :activated, :lose, :item_state, :item_number)
    end

    # item_got_userカラムに景品取得したユーザーIDを代入する
    # item_stateに "taken" を代入する
    def set_item_got_user
      if logged_in?
        if @item.item_got_user.nil? && !@item.lose?
          @item.update_attribute(:item_got_user, current_user.id)
          @item.update_attribute(:item_state, "taken")
        end
      end
    end

    # ログインユーザーがイベント作成者ならtrueを返す
    def host_user?
      if @item.post.user == current_user
        return true
      else
        return false
      end
    end

    def require_same_user
      if current_user != @item.post.user
        flash[:alert] = "ご自身以外のアカウントの閲覧・編集はできません"
        redirect_to root_path
      end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= turbo_frame_tag @item do %>
  <%= form_with(model: [@post, @item], local: true, id: "itemForm") do |f| %>

    <div class="mb-3 <%= @item.errors.include?(:name) ? "validation_errors" : "" %>">
      <%= icon("pencil-fill") %> <%= f.label "景品名", for: "postName", class: "form-label required" %>
      <%= f.text_field :name, class: "form-control", id: "itemName" %>
      <%= render 'layouts/error_messages',class: "invalid-feedback", obj: @item, key: :name %>
    </div>

    <div class="form-check mb-3">
      <%= f.check_box :lose, class: "form-check-input", id: "itemLoseCheck" ,as: :boolean %>
      <%= f.label "ハズレを設定する", class: "form-check-label", for: "itemLoseCheck" %>
      </label>
    </div>

    <div class="mb-3 row">
      <div class="col-6">
        <%= f.submit class: "btn__basic__m btn__green" %>
      </div>
      <div class="col-6">
        <%= link_to "キャンセル", @item.new_record? ? @post : post_item_path(@item.post_id, @item.id), class: "btn__basic__m" %>
      </div>
    </div>
  <% end %>

  <script>
    var itemNameInput = document.querySelector("#itemName");
    var itemLoseCheckBox = document.querySelector("#itemLoseCheck");

    itemLoseCheckBox.addEventListener("change", function(){
      if(this.checked === true){
        itemNameInput.value = "ハズレ";
      }else{
        itemNameInput.value = "";
      }
    });

    itemNameInput.addEventListener("input", function(){
      if(this.value === "ハズレ"){
        itemLoseCheckBox.checked = true;
      }else{
        itemLoseCheckBox.checked = false;
      }
    });
  </script>
<% end %>

app/views/items/_item.html.erb
<!-- <div id="<%= dom_id item %>"> -->
<%= turbo_frame_tag item do %>
  <div class="row">
    <%# 「ハズレ」を非表示にする %>
    <%# if !item.lose? %>
      <!-- No. -->
      <div class="col-3 mt-auto">
        <%= item.item_number %>
        <%#= item.lose? ? icon("dash-lg") : item.id %>
      </div>
      <%# アイテム名 %>
      <div class="col-6 mt-auto">
        <%= link_to item.name, post_item_path(item.post_id, item.id), data: { turbo_frame: item } %>
      </div>
      <%# 在庫 %>
      <div class="col-3 mt-auto">
        <% if item.item_got_user.nil? && !item.lose? %>
          <span class="text-success fw-bold"><%= icon("circle") %></span>
        <% elsif item.lose? %>
          <span class="fw-bold"><%= icon("dash-lg") %></span>
        <% else %>
          <span class="text-danger fw-bold"><%= icon("x") %></span>
        <% end %>
      </div>
      <hr class="mt-2" style="border: 1px solid #ccc">
    <%# end %>
  </div>
<% end %>

app/views/items/activate_item.html.erb
<div class="mb-5 text-center">
  <%# if @item.activated? %>
    <p>🎉おめでとうございます！！🎉</p>
    <div class="mb-3">
      <p class="fw-bold">景品 No.<%= @index %></p>
      <h3 class="fw-bold item__name__gold"><%= @item.name %></h3>
    </div>
    <p>が当たりました！！</p>
    <p>当画面を提示して景品と交換してください。</p>
    <p class="text-danger" style="font-size: 0.8em;">※景品交換までは画面をそのままにするか、スクショ保存しておくことをおすすめします。</p>
    <%= link_to icon_with_text("download", "スクリーンショットを保存する"), edit_post_item_path(@item.post_id, @item.id), class: "btn__basic__l btn__green" %>
  <%# else %>
  <!--
    <h3>😭残念！！😭</h3>
    <p>景品はすでに獲得されました。</p>
    -->
  <%# end %>
</div>

app/views/items/create.turbo_stream.erb
<%# `#items`の先頭に登録されたitemを追加する %>
<%= turbo_stream.prepend "items", @item %>

<%# 登録の入力フォームの中身を空にする %>
<%= turbo_stream.update Item.new, "" %>

<%# 景品一覧のカウント（累計・ハズレ数）を更新する %>
<%= turbo_stream.update "item-total-count", @post.items.count %>
<%= turbo_stream.update "item-lose-count", @post.items.where(lose: true).count %>

<%# Flashを表示 %>
<%= turbo_stream_flash %>

app/views/items/edit.html.erb
<h1>景品情報の編集</h1>

<%= render "form" %>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>景品の追加</h1>

<%= render "form" %>

app/views/items/show.html.erb
<% if @item.post.user == current_user %>
  <!-- イベント主催者用の表示画面 -->
  <%= turbo_frame_tag @item do %>
    <div class="mb-3">
      <p><b>景品No. </b><%= @item.item_number %></p>
      <p><b>景品名:  </b><%= @item.name %></p>
      <p><b>ID: </b><%= @item.id %></p>
      <p><b>在庫:  </b>
        <% if @item.item_got_user.nil? && !@item.lose? %>
          <span class="text-success fw-bold"><%= icon("circle") %></span>
        <% elsif @item.lose? %>
          <span class="fw-bold"><%= icon("dash-lg") %></span>
        <% else %>
          <span class="text-danger fw-bold"><%#= icon("x-lg") %>❌</span>
        <% end %>
      </p>
      <p><b>獲得者 ID:  </b><%= @item.item_got_user if !@item.item_got_user.nil? %></p>
    </div>

    <div class="mb-3">
        <%= link_to icon_with_text("caret-up-fill", "閉じる"), @item.post, class: "btn__basic__l" %>
    </div>
    <div class="mb-4 row">
      <div class="col-8">
        <%= link_to icon_with_text("pencil-square", "景品情報を編集する"), edit_post_item_path(@item.post_id, @item.id), class: "btn__basic__m btn__green", data: { turbo_frame: @item } %>
      </div>
      <div class="col-4">
        <%= link_to icon_with_text("trash", "削除"), post_item_path(@item.post_id, @item.id), class: "btn__basic__m btn__red", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %>
      </div>
    </div>
  <% end %>
<% else %>
  <!-- 参加者用の表示画面 -->
  <div class="mb-5 text-center">
    <% if @item.lose == true %>
      <div class="item__lose">
        <h3 class="m-5">😭残念！！ハズレです。</h3>
      </div>
    <% else %>
      <% if @item.item_got_user != current_user.id %>
        <div class="item__lose">
          <div class="m-5">
            <h3>😭残念！！</h3>
            <p>景品はすでに獲得されました。</p>
          </div>
        </div>
      <% else %>
        <p>🎉おめでとうございます！！🎉</p>
        <p>景品No. <b><%= @item.item_number %></b></p>
        <div class="mb-3">
          <h3 class="fw-bold item__name__gold"><%= @item.name %></h3>
        </div>
        <p>が当たりました！！</p>
        <div class="d-inline-block text-start">
          <p class="py-2 px-3 mt-1 text-bg-light"><%= icon_with_text("qr-code", "景品ID: ") %><span class=" fw-bold text-danger"><%= @item.id %></span></p>
          <p class="py-2 px-3 mt-1 text-bg-light"><%= icon_with_text("person-circle", "獲得者ID: ") %><span class=" fw-bold text-danger"><%= @item.item_got_user %></span></p>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="mb-3">
    <%= link_to icon_with_text("box-arrow-in-left", "マイページに戻る"), current_user, class: "" %>
  </div>
<% end %>

app/views/items/update.turbo_stream.erb
<%= turbo_stream.replace @item %>

<%# 景品一覧のカウント（累計・ハズレ数）を更新する %>
<%= turbo_stream.update "item-total-count", @post.items.count %>
<%= turbo_stream.update "item-lose-count", @post.items.where(lose: true).count %>

<%= turbo_stream_flash %>