config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "host_user", to: "home#host_user"
  get "signup", to: "users#new"
  get "guest_login", to: "users#guest_login"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, except: [:new] do
    member do
      get "show_qrcode"
    end
  end
  resources :posts do
    member do
      get "show_qrcodes"
      get "activation_reset"
    end
    resources :items do
      member do
        get "activate_item"
      end
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  before_create :set_post_id
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }

  private
  def set_post_id
    while self.id.blank? || User.find_by(id: self.id).present? do
      self.id = SecureRandom.base58
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy show_qrcodes activation_reset ]
  before_action :require_same_user, only: %i[ show edit update destroy ]
  before_action :require_user, only: %i[ index ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @search = @post.items.ransack(params[:q])
    @search.sorts = "created_at DESC" if @search.sorts.empty?
    @items = @search.result.page(params[:page])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to current_user, notice: "新規イベントが作成されました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to current_user, notice: "イベントが更新されました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    redirect_to current_user, notice: "イベントが削除されました", status: :see_other
  end

  # QRコードを表示・印刷する
  def show_qrcodes
  end

  # 景品の取得状態をリセットする
  def activation_reset
    @post.items.each do |item|
      if item.item_got_user? && !item.lose?
        item.update_attribute(:item_got_user, nil)
        item.update_attribute(:item_state, "exist")
      end
    end
    redirect_to @post, notice: "景品の取得状態がリセットされました"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title)
    end

    def require_same_user
      if current_user != @post.user
        flash[:alert] = "ご自身以外のアカウントの閲覧・編集はできません"
        redirect_to root_path
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, id: "postForm") do |f| %>

  <div class="mb-5 col-8 <%= post.errors.include?(:title) ? "validation_errors" : "" %>">
    <%= icon("pencil-fill") %> <%= f.label "イベント名", for: "postName", class: "form-label required" %>
    <%= f.text_field :title, class: "form-control", id: "postName"%>
    <%= render 'layouts/error_messages',class: "invalid-feedback", obj: post, key: :title %>
  </div>

  <div class="mb-3 col-8">
    <%= f.submit class: "btn__basic__m btn__green" %>
  </div>
  <div class="mb-5 col-8">
    <%= link_to "キャンセル", current_user, class: "btn__basic__m" %>
  </div>
<% end %>

<!-- イベント編集時に「削除ボタン」を表示する  -->
<% if !@post.new_record? %>
  <hr class="mt-5">
  <div class="mb-5">
    <a class="btn btn-danger" href="#" data-bs-toggle="modal" data-bs-target="#postModal"><%= icon_with_text("trash", "イベントを削除する") %></a>
  </div>

  <!-- 「削除ボタン」のモーダル -->
  <div class="modal fade" id="postModal" tabindex="-1" aria-labelledby="postModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="postModalLabel">確認</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          本当に削除しますか？
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <%= link_to icon_with_text("trash", "削除"), @post, class: "btn btn-danger", data: { turbo_method: :delete } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= link_to post.title, post %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>イベントの編集</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

app/views/posts/new.html.erb
<h1>新規イベント</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div class="mb-3">
  <%= link_to icon_with_text("box-arrow-in-left", "イベント一覧に戻る"), current_user, class: "" %>
</div>

<div class="mb-3">
  <h2><%= @post.title %></h2>
</div>


<!-- 検索フォーム -->
<div class="card shadow mt-3">
  <div class="card-header">
    <%= icon_with_text("search", "検索条件") %>
  </div>

  <div class="card-body">
    <%= search_form_for @search,
          url: post_path(@post),
          html: {
            data: {
              turbo_frame: "item-list",
              controller: "search",
              action: "input->search#submit"
               }
          } do |f| %>
      <div class="row g3 mb-3">
        <div class="col-4 col-xl-2">
          <%= f.label :item_number_start, "番号", class: "form-label fw-bold" %>
          <%= f.search_field :item_number_start, class: "form-control" %>
        </div>
        <div class="col-4 col-xl-2">
          <%= f.label :name_cont, "景品名", class: "form-label fw-bold" %>
          <%= f.search_field :name_cont, class: "form-control" %>
        </div>
        <div class="col-4 col-xl-2">
          <%= f.label :item_state_eq, "在庫", class: "form-label fw-bold" %>
          <%= f.select :item_state_eq, [['あり ◯', "exist" ], ['なし x', "taken"]],
 {include_blank: '選択なし'} ,class: 'form-select' %>
        </div>
      </div>
      <div class="">
        <%= link_to "リセット", post_path(@post), class: "btn btn-outline-secondary d-block" %>
      </div>
    <% end %>
  </div>
</div>


<!-- アイテム一覧 -->
<div class="card shadow mt-3 mb-5">
  <div class="card-header">
    <%= icon_with_text("table", "景品一覧") %>
    (累計: <span id="item-total-count" class="fw-bold text-danger"><%= @post.items.count %></span>, ハズレ数: <span id="item-lose-count" class="fw-bold text-danger"><%= @post.items.where(lose: true).count %></span>)
  </div>

  <div class="card-body mx-3">

    <%= link_to icon_with_text("plus-circle", "景品を追加"),
                    new_post_item_path(@post),
                    class: "btn__basic__m btn__green mb-3 mt-1",
                    data: { turbo_frame: "new_item" }
    %>
    <%= turbo_frame_tag "new_item" %>

    <%= turbo_frame_tag "item-list" do %>
      <div class="row py-2">
        <div class="col-3 mt-auto fw-bold">
          <%= sort_link(@search, :item_number, "No.", hide_indicator: true) %>
        </div>
        <div class="col-6 mt-auto fw-bold">
          <%= sort_link(@search, :name, "景品名", hide_indicator: true) %>
        </div>
        <div class="col-3 mt-auto fw-bold">
          <%= sort_link(@search, :item_got_user, "在庫", hide_indicator: true) %>
        </div>
        <hr class="mt-2">
      </div>
      <%# アイテム一覧を表示(turbo_stream) %>
      <div id="items">
        <%= render @items %>
      </div>
      <!--  <% @items.each_with_index do |item, index| %>
          <%# 「ハズレ」を非表示にする --%>
          <% if !item.lose? %>
            <%#-- No. --%>
            <div class="col-2 mt-auto">
              <%= index + 1 %>
              <%#= item.lose? ? icon("dash-lg") : item.id %>
            </div>
            <%#-- アイテム名 --%>
            <div class="col-7 mt-auto">
              <%= link_to item.name, post_item_path(item.post_id, item.id) %>
              <%#= link_to item.name, post_item_path(item.post_id, item.id, activation_id: item.activation_id) %>
            </div>
            <%#-- 在庫 --%>
            <div class="col-3 mt-auto">
              <% if item.item_got_user.nil? && !item.lose? %>
                <span class="text-success fw-bold"><%= icon("circle") %></span>
              <% elsif item.lose? %>
                <span class="fw-bold"><%= icon("dash-lg") %></span>
              <% else %>
                <span class="text-danger fw-bold"><%= icon("x") %></span>
              <% end %>
            </div>
            <hr class="mt-2" style="border: 1px solid #ccc">
          <% end %>
        <% end %> -->
      <div class="d-flex justify-content-end mt-3">
        <%= paginate @items %>
      </div>
    <% end %>
  </div>
</div>

<div class="mb-3 text-center">
  <%= link_to icon_with_text("qr-code", "QRコードを表示・印刷する"), show_qrcodes_post_path(@post), class: "btn__basic__l btn__w80 btn__green" %>
</div>

<div class="mb-5 text-center">
  <a class="btn__basic__l btn__w80" href="#" data-bs-toggle="modal" data-bs-target="#itemReset">景品の在庫をリセットする</a>
  <%#= link_to "アイテムの在庫をリセットする", activation_reset_post_path(@post), class: "btn__basic__l" %>
</div>


<!-- Modal -->
<div class="modal fade" id="itemReset" tabindex="-1" aria-labelledby="itemResetLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="itemResetLabel">確認</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        本当にリセットしますか？
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
        <%= link_to "リセット", activation_reset_post_path(@post), class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show_qrcodes.html.erb
<div class="no_print mb-3">
  <%= link_to icon_with_text("box-arrow-in-left", "アイテム一覧に戻る"), @post %>
</div>
<div class="no_print text-center">
  <a href="javascript:void(0)" class="btn__basic__l btn__w80 btn__green d-block mb-3" onclick="window.print();return false;"><%= icon_with_text("qr-code", "QRコードを印刷する") %></a>
  <p class="fw-bold text-danger">※倍率など細かな調整は印刷ダイアログにて行ってください。</p>
</div>

<% @post.items.each_with_index do |item, index| %>
  <div class="page d-inline-block text-center" style="border: 1px solid #ccc">
    <%#= image_tag qrcode_tag post_item_path(item.post_id, item.id) %>

    <div class="p-3">
      <span class="d-inline-block mb-1">No. <%= item.item_number %></span><br>
      <%= qrcode post_item_path(item.post_id, item.id), 2 %>
    </div>
  </div>
<% end %>

<!--
<div class="row row-cols-2 row-cols-lg-4 g-2 g-lg-1 mt-3">
  <% @post.items.each do |item| %>
    <div class="d-inline">
      <%#= image_tag qrcode_tag post_item_path(item.post_id, item.id) %>
      <p style="font-size: 0.8em"><%= item.id %></p>
    </div>

    <div class="page col mb-5">
      <div class="p-3 border text-center">
        <%#= qrcode post_item_path(item.post_id, item.id), 100 %>
        <%#= image_tag qrcode_tag post_item_path(item.post_id, item.id) %>
        <p style="font-size: 0.8em"><%#= item.id %></p>
      </div>
    </div>
  <% end %>
</div>
-->