config/routes.rb
Rails.application.routes.draw do
  root "home#top"
  get "host_user", to: "home#host_user"
  get "signup", to: "users#new"
  get "guest_login", to: "users#guest_login"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, except: [:new] do
    member do
      get "show_qrcode"
    end
  end
  resources :posts do
    member do
      get "show_qrcodes"
      get "activation_reset"
    end
    resources :items do
      member do
        get "activate_item"
      end
    end
  end

end

app/views/layouts/_error_messages.html.erb
<% if obj.errors.include?(key) %>
    <% obj.errors.full_messages_for(key).each do |error| %>
      <li style="list-style:none" class="text-danger fw-bold validation_font_size"><i class="bi bi-exclamation-circle"></i> <%= error %></li>
    <% end %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark fixed-bottom">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; QR Treasure Hunt 2022</p></div>
</footer>

app/views/layouts/_navigation.html.erb
<!-- ナビゲーションメニュー -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%#= link_to "QRコード de 宝探しゲーム", (logged_in? ? current_user : root_path), class: "navbar-brand" %>
    <%= link_to "QR Treasure Hunt", (logged_in? ? current_user : root_path), class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <% if !current_user.guest? %>
            <li class="nav-item">
              <%= link_to "新規イベント作成", new_post_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                アカウント
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                <li><%= link_to icon_with_text("person-circle","マイページ"), user_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to icon_with_text("gear","アカウント設定"), edit_user_path(current_user), class: "dropdown-item"%></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to icon_with_text("person-circle","マイページ"), user_path(current_user), class: "nav-link" %></li>
            </li>
          <% end %>
          <!-- ログアウトボタン（モーダル表示） -->
          <li class="nav-item">
            <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"><%= !current_user.guest? ? "ログアウト" : icon_with_text("box-arrow-right","退出する") %></a>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "参加する(ゲストとしてログイン)", guest_login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "イベントを作成する", host_user_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "主催者としてログイン", login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">確認</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <% if logged_in?%>
        <% if !current_user.guest? %>
          <div class="modal-body">
            本当にログアウトしますか？
          </div>
        <% else %>
          <div class="modal-body">
            一度退出すると再ログインできません。<br>
            景品交換前に退出されますと、<span class="text-danger">獲得した景品情報は全て失われるため景品交換ができなくなります。</span>
            本当によろしいですか？
          </div>
        <% end %>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <%= button_to !current_user.guest? ? "ログアウト" : "退出する", logout_path, class: "btn btn-danger", method: :delete %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QR Treasure Hunt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <div class="container mt-4">
        <div id="flash">
          <%= render 'layouts/flash_messages' %>
        </div>
        <%= yield %>
        <% if Rails.env.development? %>
          <div class="text-bg-light py-2 px-3 shadow-sm rounded">
            <p><%= debug(params) %></p>
            <p>セッションID => <%= session[:user_id] %></p>
          </div>
        <% end %>
      </div>
    </div>
    <%#= render 'layouts/footer' %>
  </body>
</html>